### ISSUE TITLE
Support for ISO datetime strings in casting Timex.Ecto.Date

### ISSUE THREAD

**Issue by tokafish** [bitwalker/timex_ecto#14]
Hi there,

Thanks for the great library. I was wondering if there would be interest in a PR to expand how strings are cast by the `Timex.Ecto.Date` type. In particular, when dealing with JSON, it would be convenient to accept ISO datetime strings as well as well as dates, and simply discard the time portion (similar to [this](https://github.com/elixir-lang/ecto/pull/965) in Ecto)

If you'd be up for adding this functionality, I'd be happy to submit a PR.

**Comment by tokafish** [comment]
I'm noticing that #13 is an open PR for this issue... so I'm closing this in favor the PR.

**Comment by bitwalker** [comment]
@tokafish Just FYI, #13 has been merged, I'll publish a new version today.
