### ISSUE TITLE
Undefined function Ecto.Time.epoch/0

### ISSUE THREAD

**Issue by martinmaillard** [bitwalker/timex_ecto#17]
`alias Ecto.Time` in `Timex.Ecto.Time` shadows `Timex.Time`, which is probably not intended. It results in the following error when calling `Timex.Ecto.Time.cast/1`.

```
** (UndefinedFunctionError) undefined function Ecto.Time.epoch/0
     stacktrace:
       (ecto) Ecto.Time.epoch()
       (timex_ecto) lib/types/time.ex:24: Timex.Ecto.Time.cast/1
       [...]
```

**Comment by tessi** [comment]
Since the #18 was merged, can this issue be closed?

**Comment by bitwalker** [comment]
I'm going to go ahead and close it since a release has been pushed as well.
