### ISSUE TITLE
Values dismatch with last version of Ecto

### ISSUE THREAD

**Issue by JustMikey** [bitwalker/timex_ecto#27]
When I migrated from `ecto` rc.3 to ecto rc.4, this error has started to appear:

```
** (Ecto.ChangeError) value `#Ecto.DateTime<2016-05-09 05:09:32>` for `MyApp.User.updated_at` in `insert` does not match type Timex.Ecto.DateTime
        (ecto) lib/ecto/repo/schema.ex:611: Ecto.Repo.Schema.dump_field!/6
        (ecto) lib/ecto/repo/schema.ex:620: anonymous fn/6 in Ecto.Repo.Schema.dump_fields!/5
        (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ecto) lib/ecto/repo/schema.ex:618: Ecto.Repo.Schema.dump_fields!/5
        (ecto) lib/ecto/repo/schema.ex:567: Ecto.Repo.Schema.dump_changes!/6
        (ecto) lib/ecto/repo/schema.ex:182: anonymous fn/11 in Ecto.Repo.Schema.do_insert/4
        (ecto) lib/ecto/repo/schema.ex:595: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
```

Looks like it's the same [issue](https://github.com/elixir-lang/ecto/issues/1412) that `calecto` had.

**Comment by philipgiuliani** [comment]
I have the same issue! Would be cool to get it fixed. For now i removed `use Timex.Ecto.Timestamps` from the model.

**Comment by unbalancedparentheses** [comment]
I am having the same issue!

**Comment by bitwalker** [comment]
I pushed some changes which may address this. They are on master if one of you can give it a go and try to see if you can produce the same error. Sorry for the trouble and the delay!

**Comment by bitwalker** [comment]
@JustMikey ping :)

**Comment by bitwalker** [comment]
Pretty sure this is working now in 1.1.3, I'll leave this open awhile longer so that one of you has a chance to report back to me that things look good on your end. So far my tests appear to work as expected.

**Comment by JustMikey** [comment]
@bitwalker I apologize for the long reply. It works correctly on my side, thank you very much.

**Comment by bitwalker** [comment]
Excellent :), thanks for the reply!

**Comment by philipgiuliani** [comment]
Also works here :)
