### ISSUE TITLE
Dependency conflict on ecto with phoenix 0.14

### ISSUE THREAD

**Issue by vsmart** [bitwalker/timex_ecto#3]
Since phoenix 0.14 uses ecto 0.13.1, and here we are trying to use 0.12.1 we get a dependency conflict. Could you update timex_ecto to use ecto 0.13.1? 
Alternatively, is there a way to bypass this conflict? 

Thanks. 😊

**Comment by bitwalker** [comment]
@vsmart Sure I can do that, just so you know though, you can always override the dependency at the top level with:

``` elixir
def deps do
  [{:ecto, "~> x.x.x", override: true}, ...]
end
```

This forces your application to use the version of ecto you specified. Hope that helps :)

**Comment by vsmart** [comment]
Thank you! :+1: :tada:

**Comment by bitwalker** [comment]
Just FYI, I pushed a new release 0.3.0 which is updated to use the latest ecto version :)

**Comment by vsmart** [comment]
Thanks again. :cake:
