### ISSUE TITLE
Last release breaks my timestamps...

### ISSUE THREAD

**Issue by erneestoc** [bitwalker/timex_ecto#35]
The crashlog looks like this... tried updating to the most up to date release of timex and ecto, and nothing... thanks for the great work.

```
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Timex.Timezone.diff/2
        (timex) lib/timezone/timezone.ex:355: Timex.Timezone.diff(nil, #<Timezone(UTC - UTC (+00:00))>)
        (timex) lib/timezone/timezone.ex:275: Timex.Timezone.convert/2
        (timex_ecto) lib/types/datetime.ex:105: Timex.Ecto.DateTime.dump/1
        (ecto) lib/ecto/type.ex:620: Ecto.Type.do_adapter_dump/3
        (ecto) lib/ecto/repo/schema.ex:606: Ecto.Repo.Schema.dump_field!/6
        (ecto) lib/ecto/repo/schema.ex:619: anonymous fn/6 in Ecto.Repo.Schema.dump_fields!/5
        (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ecto) lib/ecto/repo/schema.ex:617: Ecto.Repo.Schema.dump_fields!/5
```

**Comment by bitwalker** [comment]
Looks like the problem is that the date being dumped is nil, and that is being passed through to `Timezone.diff` which expects a valid DateTime struct. Can you find which database record caused the error, and what it's value is? That would help a bunch in troubleshooting.

**Comment by erneestoc** [comment]
I rolled back one version and started working again, and the stacktrace appears to be within your code. I hope I'm the only one affected with this though. The bug appears to be when a Timex.Ecto.DateTime is null in the db, and I'm trying to update the field.

**Comment by bitwalker** [comment]
Yes I just needed to verify what the input value from the db was, I will have a fix pushed soon.

**Comment by bitwalker** [comment]
Could you tell me what version of timex you are using? I can't reproduce the problem by just calling `Timex.Ecto.DateTime.dump(nil)`, so there must be something else involved.

**Comment by bitwalker** [comment]
Wait, I found it, I'll have a fix pushed shortly

**Comment by bitwalker** [comment]
Could you give the master branch of timex_ecto a try? I did a test with all nil values for all types, and I'm able to query and pull back records with no problems. If you are still seeing an issue, could you provide me the schema for the type which is blowing up on you? I have a test project I use, and I can add more test cases to it if something is missing.

**Comment by erneestoc** [comment]
thanks, it's working now... 👍

**Comment by bitwalker** [comment]
I'll push a new release then so you don't have to use master :)
