### ISSUE TITLE
protocol Timex.Protocol not implemented for...

### ISSUE THREAD

**Issue by justinbkay** [bitwalker/timex_ecto#40]
Phoenix 1.2.0
ecto master
timex ecto 3.0.3
timex 3.0.5

protocol Timex.Protocol not implemented for %{"day" => "6", "month" => "9", "year" => "2013"}

When using a date helper in a form the cast in the changeset gives an error about not implementing a protocol for the datastructure  %{"day" => "6", "month" => "9", "year" => "2013"}

**Comment by bitwalker** [comment]
I can implement Timex.Protocol for map, it hasn't yet been done, but is pretty straightforward. Can you open an issue [here](https://github.com/bitwalker/timex/issues)? I'll track it there.
