### ISSUE TITLE
Error when using latest Ecto rc-3

### ISSUE THREAD

**Issue by AndrewDryga** [bitwalker/timex_ecto#51]
@bitwalker Application won't build with timex_ecto:

```
Duplicated modules: 
        'Elixir.Ecto.DataType.NaiveDateTime' specified in timex_ecto and ecto
        'Elixir.Ecto.DataType.DateTime' specified in timex_ecto and ecto
        'Elixir.Ecto.DataType.Date' specified in timex_ecto and ecto
```

**Comment by Samorai** [comment]
@bitwalker Hi! 
The problem because Ecto has added the same modules but just with dump function.
https://github.com/elixir-ecto/ecto/blob/v2.1.0-rc.3/lib/ecto/data_type.ex#L55

I think we can rename your modules and add prefix Timex. I can do PR for this fix.

**Comment by bitwalker** [comment]
Fixed in master.
