### ISSUE TITLE
DateTimeWithTimezone documentation for PostgreSQL

### ISSUE THREAD

**Issue by soriyath** [bitwalker/timex_ecto#58]
I struggled to get DateTimeWIthTimezone as a column type for PostgreSQL.
Maybe you can improve the learning curve for future users by pointing to the content of [Timex Using With Ecto, #Using DateTimeWithTimezone](https://github.com/bitwalker/timex/blob/master/docs/Using%20with%20Ecto.md#using-datetimewithtimezone) in the readme of `timex_ecto`'s `Readme.md`
Thanks for the great library.

**Comment by bitwalker** [comment]
Done :)
