### ISSUE TITLE
Add timex_ecto 3.2 to hex

### ISSUE THREAD

**Issue by michallepicki** [bitwalker/timex_ecto#69]
** (Mix) No matching version for timex_ecto ~> 3.2 (from: mix.exs) in registry

**Comment by ssboisen** [comment]
Yes please, especially since timex_ecto 3.2 has deps requirement that is compat with ecto 2.2

**Comment by ssboisen** [comment]
ping @bitwalker

**Comment by isaiahdw** [comment]
Any chance we can get this updated? It would be awesome to be able to upgrade to Ecto 2.2

**Comment by bitwalker** [comment]
Done!
