### ISSUE TITLE
What's the status of timex_ecto?

### ISSUE THREAD

**Issue by michalmuskala** [bitwalker/timex_ecto#7]
It seems `timex_ecto` is quite behind both ecto and timex itself. What is the status? Is this still considered a useful library but nobody had time to maintain it, or was it obsoleted by something else?

If the issue is lack of time, I could help and bring it up to date to ecto 1.0

**Comment by bitwalker** [comment]
@michalmuskala I think it probably just needs to have the version number bumped. I'm not actively using Ecto at the moment, which is why it's fallen behind. PRs are always welcome though, and if there are bugs or issues with it, I'll gladly dive in and help fix them. I'll take care of this today :)

**Comment by bitwalker** [comment]
New release 0.5.0 was pushed.

**Comment by michalmuskala** [comment]
Thank you!
