### ISSUE TITLE
Casting a map of input loses timezone information

### ISSUE THREAD

**Issue by marieholzer** [bitwalker/timex_ecto#77]
Hi,

Our timex_ecto version is  3.1.1.

We have an HTML form in which we can edit a date. We created the “datetimetz” type as advised in the [documentation](https://hexdocs.pm/timex_ecto/Timex.Ecto.DateTimeWithTimezone.html#content).
Our problem was, each time we were using this form to edit existing data, we were losing the timezone information.

Example:
`("2018-02-05 11:30:00+00",Europe/Paris)`
becomes
`("2018-02-05 11:30:00+00",Etc/UTC)`

After some research we found that the problem appears to be lying in the implementation of [DateTimeWithTimezone.cast/1](https://github.com/bitwalker/timex_ecto/blob/master/lib/types/datetimetz.ex#L109...L119).
This function aims to transform a map of input into a proper DateTimeWithTimeZone struct. But it does not pass a timezone as a second argument to [Timex.to_datetime/2](https://github.com/bitwalker/timex_ecto/blob/master/lib/types/datetimetz.ex#L110), so it defaults to UTC, as can be seen [here](https://github.com/bitwalker/timex/blob/6ea19d1de8e23a789dc645d6d565bb5fa750e758/lib/protocol.ex#L48).
As a result we lose the timezone information when editing our data.

The simple hack we implemented to overcome this is to transform the input map into a DateTime ourselves, by calling Timex.to_datetime/2 with the timezone as second argument, before passing it to cast, which is a no op when the argument is already a DateTime struct (see [here](https://github.com/bitwalker/timex_ecto/blob/master/lib/types/datetimetz.ex#L34)).

I’m not sure about what the expected behaviour of the library is, if we’ve actually found a bug or  if we’re just misusing the library.

Cheers!

**Comment by bitwalker** [comment]
It is a bit of an abuse :P, that said it should be supported. I've updated `cast` to better handle maps of data, only using `to_datetime` if we have no other fallback.

**Comment by marieholzer** [comment]
Thank you for the update!
Though I don't understand why you say it is an abuse :)
