### ISSUE TITLE
Compilation error in file lib/types/date.ex

### ISSUE THREAD

**Issue by MattGaud2425** [bitwalker/timex_ecto#82]
Generated timex app
==> timex_ecto
Compiling 8 files (.ex)

== Compilation error in file lib/types/date.ex ==
** (CompileError) lib/types/date.ex:58: Ecto.Date.__struct__/0 is undefined, cannot expand struct Ecto.Date
    lib/types/date.ex:58: (module)
could not compile dependency :timex_ecto, "mix compile" failed. You can recompile this dependency with "mix deps.compile timex_ecto", update it with "mix deps.update timex_ecto" or clean it with "mix deps.clean timex_ecto"

**Comment by aselder** [comment]
Similar error in another file

```

== Compilation error in file lib/types/timestamptz.ex ==
** (CompileError) lib/types/timestamptz.ex:5: module Timex is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/1
    lib/types/timestamptz.ex:5: Timex.Ecto.TimestampWithTimezone (module)
```

**Comment by bitwalker** [comment]
Cannot reproduce with the latest version and Elixir 1.9. The latter error appears to be due to Timex not being loaded at all for some reason.
